version: "3"
services:
  node:
    image: "becodeorg/node"
    environment:
      NODE_ENV: "development"
      APP_PORT: 12345
    volumes:
      - "./package.json:/src/app/package.json"
      - "./node_modules:/src/app/node_modules"
      - "./bin:/src/app/bin"
    expose:
      - "12345"
      - "9229"
    ports:
      - "80:12345"
      - "9229"
    command: "nodemon --inspect=0.0.0.0:9229 --watch bin/server bin/server/index.js"
  mysql:
    image: mysql:5
    restart: always
    volumes:
      - mysql_db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: atss
      MYSQL_USER: atss
      MYSQL_PASSWORD: atss
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8001:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: atss
      PMA_PASSWORD: atss

volumes:
  mysql_db: